[package]
name = "Splitr"
version = "1.0.0"
authors = []

[addresses]
Splitr = "0x4739c234861f66e29e55ae20e8286903ff669645f29a541eb4c62a8d8c8639d0"
# Splitr = "_"

[dev-addresses]
Splitr = "0xcafe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
