[package]
name = "Splitr"
version = "1.0.0"
authors = []

[addresses]
Splitr = "0x7be1da1e5dd3d50db8f59307073e61ff6011738bb0d81ba0ed8340d75043e54a"

[dev-addresses]
Splitr = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
